server:
  port: 8081
spring:
    
  sql:
    init:
      platform:   postgresql
      mode: always   
  jpa:
    properties:
      jdbc:
        lob:
          non_contextual_creation:true
    hibernate:
      ddl-auto: update
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/salon-db
    username: salon
    password: salon
    
      
      
# meta information about the salon
salon:
  name: "AR Salon and Day Spa Services"
  address: "1234 Main Street, Anytown"
  city: "Anycity"
  state: "ND"
  zipcode: "58201"  
  phone: "555-123-4567"
    