# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: salon
      POSTGRES_PASSWORD: salon
      POSTGRES_DB: salon-db
    expose:
      - 5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
